### ISSUE TITLE
Mining Server is not connecting

### ISSUE THREAD

**Issue by hayalpc** [hpool-dev/chia-miner#668] opened 2021-07-09 16:13 UTC
Hello,

My miner is not connecting your server. How can i fix it?

Varolan bir bağlantı uzaktaki bir ana bilgisayar tarafından zorla kapatıldı =An existing connection was forcibly closed by a remote host.

time="2021-07-09T19:10:31+03:00" level=info msg="init server" file=loggers.go func=logging.CPrint line=168 tid=11 type=ws url="ws://203.107.53.48:7002/x-proxynode/ws"
time="2021-07-09T19:10:32+03:00" level=error msg="connect fail" err="read tcp 192.168.1.20:58169->203.107.53.48:7002: wsarecv: Varolan bir bağlantı uzaktaki bir ana bilgisayar tarafından zorla kapatıldı." f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect,89}" f9="{server.go,websocket.NewServer,26}" tid=11 url="ws://203.107.53.48:7002/x-proxynode/ws"
time="2021-07-09T19:10:34+03:00" level=error msg="connect fail" err="read tcp 192.168.1.20:58170->203.107.53.48:7002: wsarecv: Varolan bir bağlantı uzaktaki bir ana bilgisayar tarafından zorla kapatıldı." f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect,89}" f9="{server.go,websocket.(*Server).check,65}" tid=197 url="ws://203.107.53.48:7002/x-proxynode/ws"
time="2021-07-09T19:10:35+03:00" level=error msg="connect fail" err="read tcp 192.168.1.20:58172->203.107.53.48:7002: wsarecv: Varolan bir bağlantı uzaktaki bir ana bilgisayar tarafından zorla kapatıldı." f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect,89}" f9="{server.go,websocket.(*Server).check,65}" tid=197 url="ws://203.107.53.48:7002/x-proxynode/ws"
time="2021-07-09T19:10:37+03:00" level=error msg="connect fail" err="read tcp 192.168.1.20:58174->203.107.53.48:7002: wsarecv: Varolan bir bağlantı uzaktaki bir ana bilgisayar tarafından zorla kapatıldı." f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect,89}" f9="{server.go,websocket.(*Server).check,65}" tid=197 url="ws://203.107.53.48:7002/x-proxynode/ws"
time="2021-07-09T19:10:39+03:00" level=info msg="switch line" chain=CHIA file=loggers.go func=logging.CPrint line=168 tid=197 type=ws url="wss://chia-cd2-59c6761be4.hpool.com/x-proxynode/ws"
time="2021-07-09T19:10:39+03:00" level=error msg="connect fail" err="read tcp 192.168.1.20:58175->203.107.53.48:7002: wsarecv: Varolan bir bağlantı uzaktaki bir ana bilgisayar tarafından zorla kapatıldı." f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect,89}" f9="{server.go,websocket.(*Server).check,65}" tid=197 url="ws://203.107.53.48:7002/x-proxynode/ws"
time="2021-07-09T19:10:39+03:00" level=info msg="init server" file=loggers.go func=logging.CPrint line=168 tid=11 type=ws url="wss://chia-cd2-59c6761be4.hpool.com/x-proxynode/ws"
time="2021-07-09T19:10:40+03:00" level=error msg="connect fail" err="read tcp 192.168.1.20:58176->203.107.53.48:443: wsarecv: Varolan bir bağlantı uzaktaki bir ana bilgisayar tarafından zorla kapatıldı." f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect,89}" f9="{server.go,websocket.NewServer,26}" tid=11 url="wss://chia-cd2-59c6761be4.hpool.com/x-proxynode/ws"

Thanks

**Comment by chris-chia-chia** [comment] 2021-07-09 17:34
I just started receiving this error too, started happening about an hour ago. Seems to be blocked, but I'm running 2 miners, one on a server and my other on my PC, how come one of my miners works and not the other?

**Comment by mykaraboy** [comment] 2021-07-09 19:14
I just started receiving this error too

**Comment by hayalpc** [comment] 2021-07-09 19:16
Hey @hpool-dev help us. Our miners doesn't work.

**Comment by calberoni** [comment] 2021-07-09 19:21
Hi guys! I've the same issue. @hpool-dev

**Comment by mykaraboy** [comment] 2021-07-09 19:26
> 嗨，大家好！我有同樣的問題。@hpool-dev

你好，請問你有解決此問題了嗎?

**Comment by mykaraboy** [comment] 2021-07-09 19:27
> 嗨，大家好！我有同樣的問題。@hpool-dev

我目前已經安全最新的HP版本，也都依照以前的設定，但就是不會顯示當前任務。我們群內也有很多人都發生這樣的問題，非常的困擾。

**Comment by hayalpc** [comment] 2021-07-09 19:50
@hpool-dev we are losing money. Could you please help us? I have no contribution for 4 hours because of this problem. @hpool-dev

**Comment by j42zchia** [comment] 2021-07-09 19:55
I'm experiencing the same issue in two machines in the same network. I have another in a different location in the globe that is still working. 
Firstly I thought it would be temporary but it's already taking a while and my plots aren't online. 

here is a little extract of the log:
wsarecv: An existing connection was forcibly closed by the remote host." f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect,89}" f9="{server.go,websocket.(*Server).check,65}" tid=1073 url="wss://chia-cd1.hpool.com/x-proxynode/ws"

@hpool-dev : I know it's Friday, but gold rule says: never deploy/release at Friday :)

**Comment by hayalpc** [comment] 2021-07-09 19:57
@mykaraboy @calberoni @chris-chia-chia @j42zchia hey guys. restart your modem, change your ip address and shutdown your computer. wait just 1 min then open your modem later your computer. Now my miner is connecting the server

**Comment by j42zchia** [comment] 2021-07-09 20:15
Hi @hayalpc, thank you for your idea.

I did it but no lucky. 
What is the theory being that restart? 
Getting new public IP? Because I don't get new IP if I restart my modem... 
Updating internal network IP ? I will try that by configuration since my internal IP persists over and over.

**Comment by hayalpc** [comment] 2021-07-09 20:18
@j42zchia It was public IP. Just try your mobile hotspot if possible. I don't understand that why hpool blocks our IP addresses

**Closed as completed** 2021-07-09 21:29 UTC

**Comment by j42zchia** [comment] 2021-07-09 21:59
Is there some kind of rule that doesn't allow mora than one farmer using the same public IP? 
@hpool-dev, can you please point us for some documentation or explanation?

**Comment by j42zchia** [comment] 2021-07-09 23:21
Looks like I found an explanation here: https://github.com/hpool-dev/chia-miner/releases/tag/v1.4.1-1 
Basically in the same network it needs to have a x-proxy. This way it centralizes all the connections through it. 
So, all miners needs to point to the proxy and the proxy needs to have api-key configured.
Good luck with Chinese translations in the proxy UI  :)

**Comment by hayalpc** [comment] 2021-07-09 23:23
@j42zchia they are not help us. we need to find new pools 👎

**Comment by j42zchia** [comment] 2021-07-09 23:27
> In a local area network, only one agent needs to be opened. It is recommended that users with more than one Miner use the agent. In the agent, there is information about managing the Miner and viewing all plot files.

they have the step by step in EN, just scroll down here:
https://github.com/hpool-dev/chia-miner/releases/tag/v1.4.1-1

also here https://www.reddit.com/r/hpoolchia/comments/nzo482/hpool_proxy_setup/ you have a good explanation how to setup the configurations.

**Comment by chris-chia-chia** [comment] 2021-07-10 04:04
> 
> 
> I'm experiencing the same issue in two machines in the same network. I have another in a different location in the globe that is still working.
> Firstly I thought it would be temporary but it's already taking a while and my plots aren't online.
> 
> here is a little extract of the log:
> wsarecv: An existing connection was forcibly closed by the remote host." f7="{loggers.go,logging.CPrint,156}" f8="{server.go,websocket.(*Server).connect,89}" f9="{server.go,websocket.(*Server).check,65}" tid=1073 url="wss://chia-cd1.hpool.com/x-proxynode/ws"
> 
> @hpool-dev : I know it's Friday, but gold rule says: never deploy/release at Friday :)

exactly the same issue as me

**Comment by chris-chia-chia** [comment] 2021-07-10 04:14
> 
> 
> @j42zchia It was public IP. Just try your mobile hotspot if possible. I don't understand that why hpool blocks our IP addresses

Isn't this a temp fix? won't this problem persist later?

**Comment by chris-chia-chia** [comment] 2021-07-10 04:18
> 
> 
> > In a local area network, only one agent needs to be opened. It is recommended that users with more than one Miner use the agent. In the agent, there is information about managing the Miner and viewing all plot files.
> 
> they have the step by step in EN, just scroll down here:
> https://github.com/hpool-dev/chia-miner/releases/tag/v1.4.1-1
> 
> also here https://www.reddit.com/r/hpoolchia/comments/nzo482/hpool_proxy_setup/ you have a good explanation how to setup the configurations.

but can i do this on another machine in another part of the world? My server and pc use the same api but are both on different continents. If I can do this wouldn't this cause timeouts?

**Comment by chris-chia-chia** [comment] 2021-07-10 04:34
> 
> 
> Hi @hayalpc, thank you for your idea.
> 
> I did it but no lucky.
> What is the theory being that restart?
> Getting new public IP? Because I don't get new IP if I restart my modem...
> Updating internal network IP ? I will try that by configuration since my internal IP persists over and over.

For now I'm using my VPN as a temporary fix just to keep my revenue coming in.

**Comment by j42zchia** [comment] 2021-07-10 11:07
> > > In a local area network, only one agent needs to be opened. It is recommended that users with more than one Miner use the agent. In the agent, there is information about managing the Miner and viewing all plot files.
> > 
> > 
> > they have the step by step in EN, just scroll down here:
> > https://github.com/hpool-dev/chia-miner/releases/tag/v1.4.1-1
> > also here https://www.reddit.com/r/hpoolchia/comments/nzo482/hpool_proxy_setup/ you have a good explanation how to setup the configurations.
> 
> but can i do this on another machine in another part of the world? My server and pc use the same api but are both on different continents. If I can do this wouldn't this cause timeouts?

I also have this scenario and as the other machine has another public address it looks it's accepted. 
Meanwhile in my place I have two machines farming and I'm kind of banned because of that.
I already try the approach of the xProxy but now the issue is in the proxy since the proxy is getting the same exact log connection error.
